'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowDownLeft,ArrowUpRight,Check,Copy,FilePenLine,Mail,RefreshCw,Save,Trash2,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {applicationStatuses,gmailMessageUrl,type Application,type ApplicationEmail,type ApplicationStatus} from '@/lib/application-contract';
import {applicationTools} from '@/lib/application-tools';
import {type EmailDraft} from '@/lib/draft-contract';
import {type Organisation} from '@/lib/data';
type Result={sentDrafts?:EmailDraft[];application?:Application;emails?:ApplicationEmail[];applications?:Application[];total?:number;emailTotal?:number;offset?:number;error?:string};
export function useApplications(){
 const[applications,setApplications]=useState<Application[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loadError,setLoadError]=useState(''),[needsSignIn,setNeedsSignIn]=useState(false);
 const serial=useRef(0),working=useRef(false);
 const refresh=useCallback(async(offset=0)=>{if(working.current)return;const version=++serial.current;try{const response=await fetch('/api/applications?offset='+offset,{cache:'no-store'}),value=await response.json() as Result;if(version!==serial.current)return;if(!response.ok){if(response.status===401){setNeedsSignIn(true);setApplications([]);}throw new Error(value.error||'Bewerbungen nicht erreichbar.');}setApplications(old=>offset?[...new Map([...old,...value.applications!].map(a=>[a.id,a])).values()]:value.applications!);setTotal(value.total||0);setNeedsSignIn(false);setLoadError('');}catch(e){if(version===serial.current)setLoadError(e instanceof Error?e.message:'Bewerbungen nicht erreichbar.');}finally{if(version===serial.current)setLoading(false);}},[]);
 const invoke=useCallback(async(tool:string,args:unknown)=>{if(working.current)throw new Error('Bitte den laufenden Vorgang abwarten.');working.current=true;++serial.current;setBusy(true);setError('');try{const response=await fetch('/api/collection-tools',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tool,arguments:args})}),value=await response.json() as Result;if(!response.ok){if(response.status===401){setNeedsSignIn(true);setApplications([]);}throw new Error(value.error||'Bewerbung konnte nicht geladen werden.');}return value;}catch(e){setError(e instanceof Error?e.message:'Bewerbungen nicht erreichbar.');throw e;}finally{working.current=false;setBusy(false);if(tool!=='get_application')void refresh();}},[refresh]);
 useEffect(()=>{void refresh();const focus=()=>{if(document.visibilityState==='visible')void refresh();};window.addEventListener('focus',focus);window.addEventListener('zivi-applications-changed',focus);const timer=setInterval(focus,15000);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);window.removeEventListener('zivi-applications-changed',focus);};},[refresh]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();for(const tool of applicationTools){try{Promise.resolve(context.registerTool({...tool,annotations:{readOnlyHint:tool.readOnly,untrustedContentHint:true},execute:(args:unknown)=>invoke(tool.name,args)},{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();},[invoke]);
 return{applications,total,loading,busy,error:error||loadError,needsSignIn,refresh,invoke};
}
export function ApplicationBadge({application}:{application:Application|undefined}){return application?<span className={'application-badge status-'+application.effectiveStatus}>{applicationStatuses[application.effectiveStatus]}</span>:null;}
const date=(value:string)=>new Intl.DateTimeFormat('de-AT',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Vienna'}).format(new Date(value));
export function ApplicationsDialog({model,open,onOpenChange,organisation,initialId,onDrafts,onCompose}:{model:ReturnType<typeof useApplications>;open:boolean;onOpenChange:(v:boolean)=>void;organisation:Organisation|null;initialId:string|null;onDrafts:()=>void;onCompose:(code:number)=>void}){
 const[selected,setSelected]=useState<Application|null>(null),[emails,setEmails]=useState<ApplicationEmail[]>([]),[status,setStatus]=useState<ApplicationStatus>('automatic'),[notes,setNotes]=useState(''),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[deleting,setDeleting]=useState(false),[pending,setPending]=useState<(()=>void)|null>(null);
 const[emailTotal,setEmailTotal]=useState(0),[sentDrafts,setSentDrafts]=useState<EmailDraft[]>([]);
 const serial=useRef(0),dirty=!!selected&&(status!==selected.status||notes!==selected.notes);
 const accept=(r:Result)=>{if(r.application){setSelected(r.application);setStatus(r.application.status);setNotes(r.application.notes);setEmails(r.emails||[]);setSentDrafts(r.sentDrafts||[]);setEmailTotal(r.emailTotal||0);}};
 const load=async(id:string)=>{const version=++serial.current;setNotice('');setDeleting(false);try{const r=await model.invoke('get_application',{applicationId:id});if(version===serial.current)accept(r);}catch{}};
 const guard=(fn:()=>void)=>{if(model.busy)return;if(dirty)setPending(()=>fn);else fn();};
 useEffect(()=>{if(open){setSelected(null);setEmails([]);setPending(null);setNotice('');setDeleting(false);void model.refresh();const found=initialId||model.applications.find(a=>a.organisationCode===organisation?.code)?.id;if(found)void load(found);}else ++serial.current;},[open,initialId,organisation]);
 useEffect(()=>{if(!open||!dirty)return;const unload=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload);},[open,dirty]);
 const summary=selected?model.applications.find(a=>a.id===selected.id):undefined;
 const changed=!!selected&&!!summary&&summary.revision>selected.revision;
 const save=async()=>{if(!selected)return false;try{accept(await model.invoke('update_application',{applicationId:selected.id,expectedRevision:selected.revision,status,notes}));setNotice('Gespeichert');return true;}catch{return false;}};
 const copyPrompt=async()=>{const prompt=`Aktualisiere meine Zivildienst-Bewerbungen in Zivi Atlas${selected?' für '+selected.organisationTitle:''}. Suche in meinem verbundenen Gmail nach tatsächlich gesendeten Bewerbungen und Antworten, lies die Nachrichten und importiere sie mit Zivildienst Collections. Ordne sie anhand der offiziellen Kontaktdaten den Einrichtungen zu. Übernimm bestätigte Zusagen oder Absagen in den Bewerbungsstand. Sende keine E-Mails.`;try{await navigator.clipboard.writeText(prompt);setNotice('Auftrag kopiert – in ChatGPT mit Gmail und Zivildienst Collections einfügen.');}catch{setNotice(prompt);}};
 const visible=model.applications.filter(a=>!query||`${a.organisationTitle} ${applicationStatuses[a.effectiveStatus]}`.toLocaleLowerCase('de').includes(query.toLocaleLowerCase('de')));
 return <Dialog open={open} onOpenChange={v=>{if(!v)guard(()=>onOpenChange(false));}}><DialogContent aria-describedby={undefined} className="drafts-dialog applications-dialog" showCloseButton={false}>
  <header className="drafts-heading"><div><DialogTitle>Bewerbungen</DialogTitle></div><div className="application-heading-actions"><button className="draft-save" onClick={()=>guard(onDrafts)}><FilePenLine size={16}/>Entwürfe</button><button className="close-detail" aria-label="Bewerbungen schließen" disabled={model.busy} onClick={()=>guard(()=>onOpenChange(false))}><X size={20}/></button></div></header>
  {pending&&<div className="draft-prompt" role="alert"><p>Änderungen zuerst speichern?</p><div><button disabled={model.busy} onClick={()=>setPending(null)}>Zurück</button><button disabled={model.busy} onClick={()=>{const next=pending;setPending(null);next();}}>Verwerfen</button><button className="primary-button" disabled={model.busy} onClick={async()=>{if(await save()){const next=pending;setPending(null);next();}}}>Speichern & weiter</button></div></div>}
  {model.error&&<div className="collection-error" role="alert">{model.error}{model.needsSignIn?<a href={'/signin-with-chatgpt?return_to='+encodeURIComponent(initialId?'/?application='+encodeURIComponent(initialId):'/')} target="_top">Mit ChatGPT anmelden</a>:<button disabled={model.busy} onClick={()=>selected?guard(()=>void load(selected.id)):void model.refresh()}>Neu laden</button>}</div>}
  {!model.needsSignIn&&<div className="drafts-workspace"><aside className="drafts-sidebar" aria-label="Meine Bewerbungen"><div className="application-search"><input placeholder="Bewerbung suchen" aria-label="Bewerbung suchen" value={query} onChange={e=>setQuery(e.target.value)}/><small>{model.total} {model.total===1?'Bewerbung':'Bewerbungen'}</small></div><div className="draft-list">{model.loading?<p className="draft-list-empty">Bewerbungen werden geladen…</p>:!visible.length?<p className="draft-list-empty">{query?'Keine passende Bewerbung.':'Noch keine Bewerbungen importiert.'}</p>:visible.map(a=><button key={a.id} className={'draft-list-item '+(selected?.id===a.id?'selected':'')} disabled={model.busy} onClick={()=>guard(()=>void load(a.id))}><strong>{a.organisationTitle}</strong><ApplicationBadge application={a}/><small>{a.messageCount} E-Mails{a.lastMessageAt?' · '+new Intl.DateTimeFormat('de-AT',{day:'numeric',month:'short'}).format(new Date(a.lastMessageAt)):''}</small></button>)}{model.applications.length<model.total&&<button className="draft-new" disabled={model.busy} onClick={()=>void model.refresh(model.applications.length)}>Weitere laden</button>}</div><button className="draft-new" onClick={copyPrompt}><Copy size={15}/>Mit ChatGPT aktualisieren</button></aside>
  <section className="draft-editor application-detail" aria-label="Bewerbungsverlauf">{!selected?<div className="draft-empty"><Mail size={32}/><p>{organisation?organisation.title:'Wähle eine Bewerbung, um E-Mails und Antworten zu sehen.'}</p>{organisation&&<button className="primary-button" disabled={model.busy} onClick={async()=>{try{accept(await model.invoke('track_application',{organisationCode:organisation.code}));}catch{}}}>Bewerbung verfolgen</button>}<p className="draft-footnote">Gmail-Nachrichten werden auf deinen Auftrag über ChatGPT importiert.</p></div>:<>
   <div className="application-title"><h2>{selected.organisationTitle}</h2><span>{selected.contactEmail}</span><button className="draft-mail-app" onClick={()=>guard(()=>onCompose(selected.organisationCode))}><FilePenLine size={16}/>E-Mail-Entwürfe</button></div>
   {changed&&<div className="draft-conflict">Ein neuer Stand ist verfügbar.<button disabled={model.busy} onClick={()=>guard(()=>void load(selected.id))}><RefreshCw size={13}/>Neu laden</button></div>}
   <div className="application-status-editor"><label id="application-status-label">Bewerbungsstand</label><Select value={status} onValueChange={v=>setStatus(v as ApplicationStatus)} disabled={model.busy}><SelectTrigger aria-labelledby="application-status-label"><SelectValue/></SelectTrigger><SelectContent position="popper" className="application-status-menu">{Object.entries(applicationStatuses).map(([value,label])=><SelectItem key={value} value={value}>{value==='automatic'?'Automatisch nach E-Mail-Verlauf':label}</SelectItem>)}</SelectContent></Select><label className="application-notes">Notizen<textarea value={notes} maxLength={4000} disabled={model.busy} onChange={e=>setNotes(e.target.value)} placeholder="Nächster Schritt, Rückmeldung, Gespräch…"/></label><div className="draft-save-row"><button className="draft-save" disabled={!dirty||model.busy} onClick={save}><Save size={15}/>Speichern</button><span className="draft-status">{dirty?'Ungespeicherte Änderungen':applicationStatuses[selected.effectiveStatus]}</span><button className="draft-icon" aria-label="Bewerbung entfernen" onClick={()=>setDeleting(true)}><Trash2 size={16}/></button></div>{deleting&&<div className="draft-prompt"><p>Bewerbung und importierte Kopien entfernen? Die Originale bleiben in Gmail.</p><div><button onClick={()=>setDeleting(false)}>Abbrechen</button><button className="draft-danger" disabled={model.busy} onClick={async()=>{try{await model.invoke('delete_application',{applicationId:selected.id,expectedRevision:selected.revision});setSelected(null);setEmails([]);setDeleting(false);}catch{}}}>Entfernen</button></div></div>}</div>
   <div className="application-timeline"><div className="application-timeline-heading"><h3>E-Mail-Verlauf <span>{emailTotal+sentDrafts.length}</span></h3>{selected.lastImportAt&&<p>Aus Gmail · Stand {date(selected.lastImportAt)}</p>}</div>{sentDrafts.map(draft=><details className="application-email sent" key={draft.id}><summary><span className="email-direction"><ArrowUpRight size={15}/>Gesendet</span><time>{draft.sentAt?date(draft.sentAt):''}</time><strong>{draft.subject||'Ohne Betreff'}</strong><span className="email-preview">Gespeicherte Entwurfskopie</span></summary><div className="application-email-content"><p>An: {draft.recipient}</p><p className="application-email-body">{draft.body}</p>{draft.attachments.map(file=><p key={file.id}><a href={file.downloadUrl} download>{file.filename}</a></p>)}</div></details>)}{!emails.length&&!sentDrafts.length?<p className="draft-footnote">Noch keine gesendeten E-Mails importiert. Ein Entwurf erscheint erst nach dem Senden und Import hier.</p>:emails.map(email=><details className={'application-email '+email.direction} key={email.id}><summary><span className="email-direction">{email.direction==='sent'?<ArrowUpRight size={15}/>:<ArrowDownLeft size={15}/>} {email.direction==='sent'?'Gesendet':'Antwort'}</span><time dateTime={email.occurredAt}>{date(email.occurredAt)}</time><strong>{email.subject||'Ohne Betreff'}</strong><span className="email-preview">{email.body.replace(/\s+/g,' ').slice(0,125)}</span></summary><div className="application-email-content"><dl><dt>Von</dt><dd>{email.from}</dd><dt>An</dt><dd>{email.to}</dd>{email.cc&&<><dt>Cc</dt><dd>{email.cc}</dd></>}</dl><p className="application-email-body">{email.body}</p>{email.bodyTruncated&&<p className="draft-footnote">Gekürzte Kopie. Vollständige Nachricht in Gmail öffnen.</p>}<a href={gmailMessageUrl(email)} target="_blank" rel="noopener noreferrer">In Gmail öffnen <ArrowUpRight size={14}/></a></div></details>)}{emails.length<emailTotal&&<button className="draft-new" disabled={model.busy} onClick={async()=>{try{const r=await model.invoke('get_application',{applicationId:selected.id,offset:emails.length});setEmails(old=>[...new Map([...old,...(r.emails||[])].map(e=>[e.id,e])).values()]);setEmailTotal(r.emailTotal||0);}catch{}}}>Ältere E-Mails laden</button>}</div>
  </>}</section></div>}{notice&&<div className="application-notice" role="status"><Check size={15}/>{notice}</div>}
 </DialogContent></Dialog>;
}
