const id={type:'string',description:'Sammlungs-ID aus list_collections.'};
const name={type:'string',minLength:1,maxLength:80};
const codes={type:'array',items:{type:'integer',minimum:1},minItems:1,maxItems:100,description:'Einrichtungsnummern (code), keine Einsatzort-IDs. Über search_einrichtungen ermitteln.'};
const schema=(properties:Record<string,unknown>,required:string[]=[])=>({type:'object',properties,required,additionalProperties:false});
export const collectionTools=[
  {name:'list_collections',title:'Sammlungen anzeigen',description:'List all collections and saved Einrichtungen for the signed-in user. Returns collection IDs and institution codes.',inputSchema:schema({}),readOnly:true},
  {name:'create_collection',title:'Sammlung erstellen',description:'Create a saved collection, optionally adding up to 100 verified Einrichtungen. Returns the created ID and current collections.',inputSchema:schema({name,organisationCodes:codes},['name']),readOnly:false},
  {name:'rename_collection',title:'Sammlung umbenennen',description:'Rename an existing collection without changing its saved Einrichtungen.',inputSchema:schema({collectionId:id,name},['collectionId','name']),readOnly:false},
  {name:'delete_collection',title:'Sammlung löschen',description:'Delete a collection and all its saved memberships. Does not delete any official Einrichtung. Use only when the user asks to delete that collection.',inputSchema:schema({collectionId:id},['collectionId']),readOnly:false},
  {name:'add_to_collection',title:'Einrichtungen speichern',description:'Add up to 100 Einrichtungen by verified institution code to a collection. Existing entries are preserved and duplicates are ignored.',inputSchema:schema({collectionId:id,organisationCodes:codes},['collectionId','organisationCodes']),readOnly:false},
  {name:'remove_from_collection',title:'Einrichtungen entfernen',description:'Remove specified Einrichtungen from one collection. Other collection memberships and official data remain unchanged.',inputSchema:schema({collectionId:id,organisationCodes:codes},['collectionId','organisationCodes']),readOnly:false},
  {name:'search_einrichtungen',title:'Einrichtungen suchen',description:'Search official Einrichtungen and get stable codes for saving. Query matches name, city, postcode and code. Date filters use YYYY-MM. region uses BURGENLAND, CARINTHIA, LOWER_AUSTRIA, UPPER_AUSTRIA, SALZBURG, STYRIA, TYROL, VORARLBERG or VIENNA. Availability is for the entire Einrichtung, not an individual Einsatzort.',inputSchema:schema({query:{type:'string',maxLength:200},region:{type:'string'},branch:{type:'string'},from:{type:'string'},until:{type:'string'},freeOnly:{type:'boolean'},limit:{type:'integer',minimum:1,maximum:100},offset:{type:'integer',minimum:0}}),readOnly:true},
];
