export type Address={address:string|null;zipCode:string|null;city:string|null;region:string|null;areaCode:string|null;districtCode:string|null};
export type Slot={date:number[];capacity:number;used:number;available:number;transferSlots:number};
export type Agency={name:string;address:Address;location:{latitude:number|null;longitude:number|null}};
export type Organisation={code:number;title:string;branch:string;branchCode:string;activity:string;name:string;phone:string;email:string;homepage:string;info:string;address:Address;owner:{title:string;address:Address};agencies:Agency[];slots:Slot[]};
export type Dataset={content:Organisation[];totalCount:number;lastUpdated:number;source?:string};
export type Place={id:string;org:Organisation;agency:Agency;lat:number|null;lng:number|null;search:string};
export type Filters={query:string;region:string;branch:string;from:string;until:string;freeOnly:boolean};
export const regions:Record<string,string>={BURGENLAND:'Burgenland',CARINTHIA:'Kärnten',LOWER_AUSTRIA:'Niederösterreich',UPPER_AUSTRIA:'Oberösterreich',SALZBURG:'Salzburg',STYRIA:'Steiermark',TYROL:'Tirol',VORARLBERG:'Vorarlberg',VIENNA:'Wien'};
export const categories:Record<string,string>={'1':'Krankenanstalten','2':'Rettungswesen','3a':'Sozialhilfe','3b':'Behindertenhilfe','3c':'Landwirtschaftliche Hilfe','3d':'Altenbetreuung','3e':'Gesundheit & Krankenbetreuung','3f':'Suchtbetreuung','3g':'Justizanstalten','4':'Flüchtlingsbetreuung','5':'Katastrophenhilfe & Zivilschutz','6a':'Zivile Landesverteidigung','6b':'Öffentliche Sicherheit','6c':'Gedenkstätten','6d':'Umweltschutz','6e':'Jugendarbeit','6f':'Kinderbetreuung','6g':'Integration & Beratung'};
export const defaultFilters:Filters={query:'',region:'all',branch:'all',from:'all',until:'all',freeOnly:false};
export const isoDate=(a:number[])=>a.map((v,i)=>String(v).padStart(i?2:4,'0')).join('-');
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Vienna',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const normalise=(s:string)=>s.toLocaleLowerCase('de-AT').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss');
export function flatten(data:Dataset):Place[]{return data.content.flatMap(org=>org.agencies.map((agency,index)=>{const{latitude:lat,longitude:lng}=agency.location;const valid=typeof lat==='number'&&typeof lng==='number'&&Math.abs(lat)<=90&&Math.abs(lng)<=180&&!(lat===0&&lng===0);return{id:`${org.code}-${index}`,org,agency,lat:valid?lat:null,lng:valid?lng:null,search:normalise([agency.name,org.title,agency.address.city,agency.address.zipCode,agency.address.address,org.code].join(' '))};}));}
export function matchingSlots(org:Organisation,f:Filters,day=today()){return org.slots.filter(s=>{const d=isoDate(s.date);return d>=day&&(f.from==='all'||d.slice(0,7)>=f.from)&&(f.until==='all'||d.slice(0,7)<=f.until);}).sort((a,b)=>isoDate(a.date).localeCompare(isoDate(b.date)));}
export function filterPlaces(places:Place[],f:Filters,day=today()){if(f.from!=='all'&&f.until!=='all'&&f.from>f.until)return[];const words=normalise(f.query.trim()).split(/\s+/).filter(Boolean);const eligible=new Map<number,boolean>();return places.filter(p=>{if(f.region!=='all'&&p.agency.address.region!==f.region)return false;if(f.branch!=='all'&&p.org.branchCode!==f.branch)return false;if(!words.every(w=>p.search.includes(w)))return false;if(!eligible.has(p.org.code)){const slots=matchingSlots(p.org,f,day);eligible.set(p.org.code,f.freeOnly?slots.some(s=>s.available>0):(f.from!=='all'||f.until!=='all')?slots.length>0:true);}return eligible.get(p.org.code);});}
export const category=(o:Organisation)=>categories[o.branchCode]||o.branch;
export function safeUrl(raw:string){try{const u=new URL(raw);return['http:','https:'].includes(u.protocol)?u.href:undefined;}catch{return undefined;}}
