const id={type:'string',format:'uuid'},revision={type:'integer',minimum:1},recipient={type:'string',maxLength:254},subject={type:'string',maxLength:200},body={type:'string',maxLength:8000},organisationCode={type:'integer',minimum:1};
const schema=(properties:Record<string,unknown>,required:string[]=[])=>({type:'object',properties,required,additionalProperties:false});
export const draftTools=[
  {name:'list_email_drafts',title:'E-Mail-Entwürfe anzeigen',description:'List the connected user’s saved Zivi Atlas email drafts (summaries without bodies), optionally for an Einrichtung or a subject/contact search. Returns total and offset for pagination. These are drafts in the map, not Gmail drafts or sent messages.',inputSchema:schema({organisationCode,query:{type:'string',maxLength:120},limit:{type:'integer',minimum:1,maximum:100},offset:{type:'integer',minimum:0,maximum:100000}}),readOnly:true},
  {name:'get_email_draft',title:'E-Mail-Entwurf öffnen',description:'Read one saved email draft with its current revision and links to edit in Zivi Atlas or open Gmail/the mail app. Present draftUrl to the user for review. Composer links do not send email.',inputSchema:schema({draftId:id},['draftId']),readOnly:true},
  {name:'create_email_draft',title:'E-Mail entwerfen',description:'Save an unsent email draft in Zivi Atlas. For an Einrichtung, first search for its verified code; recipient and subject are prefilled from official data when omitted. Returns the saved draft, revision and review/composer links. Never sends email or creates a Gmail draft.',inputSchema:schema({organisationCode,recipient,subject,body}),readOnly:false},
  {name:'update_email_draft',title:'E-Mail-Entwurf bearbeiten',description:'Replace recipient, subject and body of a saved draft. Read it first and pass its expectedRevision to avoid overwriting changes made in the website or another chat. A revision conflict requires rereading and reconciling edits. Never sends email.',inputSchema:schema({draftId:id,expectedRevision:revision,recipient,subject,body},['draftId','expectedRevision','recipient','subject','body']),readOnly:false},
  {name:'delete_email_draft',title:'E-Mail-Entwurf löschen',description:'Delete one Zivi Atlas draft only when the user asks. Requires its current expectedRevision; does not modify Gmail or any sent email.',inputSchema:schema({draftId:id,expectedRevision:revision},['draftId','expectedRevision']),readOnly:false},
];
